/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.app;

import org.springframework.context.annotation.AnnotationConfigApplicationContext;


public class App {
    public static void main(String[] args) {
        AnnotationConfigApplicationContext configApplicationContext = new AnnotationConfigApplicationContext();
    }
}
